import {
  Home,
  SignUp,
  LogIn,
  EventList,
  AddEvent,
  EditEvent,
  AssignCommittee,
  PreviewEvent,
  GuestList,
  AddGuest,
  EditGuest,
  CommitteeList,
  AddCommittee,
  EditCommittee,
  AssignEvent,
  AnnouncementList,
  AddAnnouncement,
  EditAnnouncement,
  LotteryList,
  Lottery,
  AttendanceList,
  Attendance,
  Event,
  EventAnnouncementList,
  EventAnnouncementDetail,
  SandBox,
} from "../Pages";

const routes = [
  { path: "/signup", component: SignUp },
  { path: "/login/:token?", component: LogIn },
  { path: "/manage-event/event-list", component: EventList },
  { path: "/manage-event/add-event", component: AddEvent },
  { path: "/manage-event/edit-event/:id", component: EditEvent },
  { path: "/manage-event/assign-committee/:id", component: AssignCommittee },
  { path: "/manage-event/preview-event/:id?", component: PreviewEvent },
  { path: "/manage-event/guest-list/:id?", component: GuestList },
  { path: "/manage-event/add-guest/:id", component: AddGuest },
  { path: "/manage-event/edit-guest/:id", component: EditGuest },
  { path: "/manage-event/committee-list", component: CommitteeList },
  { path: "/manage-event/add-committee", component: AddCommittee },
  { path: "/manage-event/edit-committee/:id", component: EditCommittee },
  { path: "/manage-event/assign-event/:id", component: AssignEvent },
  { path: "/manage-event/announcement-list/:id?", component: AnnouncementList },
  { path: "/manage-event/add-announcement/:id", component: AddAnnouncement },
  { path: "/manage-event/edit-announcement/:id", component: EditAnnouncement },
  { path: "/manage-event/lottery-list", component: LotteryList },
  { path: "/manage-event/lottery/:id", component: Lottery },
  { path: "/manage-event/attendance-list", component: AttendanceList },
  { path: "/manage-event/attendance/:id", component: Attendance },
  { path: "/event", component: Event },
  { path: "/event/announcement-list", component: EventAnnouncementList },
  {
    path: "/event/announcement-detail/:id",
    component: EventAnnouncementDetail,
  },
  { path: "/sandbox", component: SandBox },
  { path: "/", component: Home },
];

export default routes;
